// <auto-generated />
namespace SpacedRepetitionSystem
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Messages
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="Messages"/> class.
        /// </summary>
        public Messages()
        {
        }

        /// <summary>
        /// Gets the resource string indexed by the AddFieldCommandToolTip key.
        /// </summary>
        public static string AddFieldCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("AddFieldCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Close key.
        /// </summary>
        public static string Close
        {
            get
            {
                return Messages.ResourceManager.GetString("Close", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo CultureInfo { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the DeleteCardDialogText key.
        /// </summary>
        public static string DeleteCardDialogText
        {
            get
            {
                return Messages.ResourceManager.GetString("DeleteCardDialogText", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DeleteCardDialogTitle key.
        /// </summary>
        public static string DeleteCardDialogTitle
        {
            get
            {
                return Messages.ResourceManager.GetString("DeleteCardDialogTitle", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DeleteCardTemplateDialogText key.
        /// </summary>
        public static string DeleteCardTemplateDialogText
        {
            get
            {
                return Messages.ResourceManager.GetString("DeleteCardTemplateDialogText", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DeleteCardTemplateDialogTitle key.
        /// </summary>
        public static string DeleteCardTemplateDialogTitle
        {
            get
            {
                return Messages.ResourceManager.GetString("DeleteCardTemplateDialogTitle", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DeleteDeckDialogText key.
        /// </summary>
        public static string DeleteDeckDialogText
        {
            get
            {
                return Messages.ResourceManager.GetString("DeleteDeckDialogText", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DeleteDeckDialogTitle key.
        /// </summary>
        public static string DeleteDeckDialogTitle
        {
            get
            {
                return Messages.ResourceManager.GetString("DeleteDeckDialogTitle", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Difficult key.
        /// </summary>
        public static string Difficult
        {
            get
            {
                return Messages.ResourceManager.GetString("Difficult", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DoesNotKnow key.
        /// </summary>
        public static string DoesNotKnow
        {
            get
            {
                return Messages.ResourceManager.GetString("DoesNotKnow", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Easy key.
        /// </summary>
        public static string Easy
        {
            get
            {
                return Messages.ResourceManager.GetString("Easy", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the HomePageTitle key.
        /// </summary>
        public static string HomePageTitle
        {
            get
            {
                return Messages.ResourceManager.GetString("HomePageTitle", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NewCard key.
        /// </summary>
        public static string NewCard
        {
            get
            {
                return Messages.ResourceManager.GetString("NewCard", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NewDeck key.
        /// </summary>
        public static string NewDeck
        {
            get
            {
                return Messages.ResourceManager.GetString("NewDeck", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NewTemplate key.
        /// </summary>
        public static string NewTemplate
        {
            get
            {
                return Messages.ResourceManager.GetString("NewTemplate", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Next key.
        /// </summary>
        public static string Next
        {
            get
            {
                return Messages.ResourceManager.GetString("Next", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Practice key.
        /// </summary>
        public static string Practice
        {
            get
            {
                return Messages.ResourceManager.GetString("Practice", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeCommandToolTip key.
        /// </summary>
        public static string PracticeCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeDifficultCommandToolTip key.
        /// </summary>
        public static string PracticeDifficultCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeDifficultCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeDoesNotKnowToolTip key.
        /// </summary>
        public static string PracticeDoesNotKnowToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeDoesNotKnowToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeEasyCommandToolTip key.
        /// </summary>
        public static string PracticeEasyCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeEasyCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeNextCommandToolTip key.
        /// </summary>
        public static string PracticeNextCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeNextCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticePageSummaryTitle key.
        /// </summary>
        public static string PracticePageSummaryTitle
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticePageSummaryTitle", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticePageTitle key.
        /// </summary>
        public static string PracticePageTitle
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticePageTitle", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeShowResultCommandToolTip key.
        /// </summary>
        public static string PracticeShowResultCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeShowResultCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PracticeStatistics key.
        /// </summary>
        public static string PracticeStatistics
        {
            get
            {
                return Messages.ResourceManager.GetString("PracticeStatistics", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the RemoveFieldCommandToolTip key.
        /// </summary>
        public static string RemoveFieldCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("RemoveFieldCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (Messages.resourceManager == null)
                {
                    Messages.resourceManager = new ResourceManager("SpacedRepetitionSystem.Messages", typeof(Messages).GetTypeInfo().Assembly);
                }

                return Messages.resourceManager;
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SearchCards key.
        /// </summary>
        public static string SearchCards
        {
            get
            {
                return Messages.ResourceManager.GetString("SearchCards", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SearchCommandToolTip key.
        /// </summary>
        public static string SearchCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("SearchCommandToolTip", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SearchDecks key.
        /// </summary>
        public static string SearchDecks
        {
            get
            {
                return Messages.ResourceManager.GetString("SearchDecks", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SearchTemplates key.
        /// </summary>
        public static string SearchTemplates
        {
            get
            {
                return Messages.ResourceManager.GetString("SearchTemplates", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Show key.
        /// </summary>
        public static string Show
        {
            get
            {
                return Messages.ResourceManager.GetString("Show", Messages.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the ShowStatisticsCommandToolTip key.
        /// </summary>
        public static string ShowStatisticsCommandToolTip
        {
            get
            {
                return Messages.ResourceManager.GetString("ShowStatisticsCommandToolTip", Messages.CultureInfo);
            }
        }
    }
}