//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpacedRepetitionSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpacedRepetitionSystem.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Deck.
        /// </summary>
        internal static string AddDeck {
            get {
                return ResourceManager.GetString("AddDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        internal static string AddTemplate {
            get {
                return ResourceManager.GetString("AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already an user?.
        /// </summary>
        internal static string AlreadyUser {
            get {
                return ResourceManager.GetString("AlreadyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Cards.
        /// </summary>
        internal static string DueCards {
            get {
                return ResourceManager.GetString("DueCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field 1.
        /// </summary>
        internal static string Field_1 {
            get {
                return ResourceManager.GetString("Field_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field 2.
        /// </summary>
        internal static string Field_2 {
            get {
                return ResourceManager.GetString("Field_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field 3.
        /// </summary>
        internal static string Field_3 {
            get {
                return ResourceManager.GetString("Field_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Count.
        /// </summary>
        internal static string FieldCount {
            get {
                return ResourceManager.GetString("FieldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Properties.
        /// </summary>
        internal static string MainProperties {
            get {
                return ResourceManager.GetString("MainProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainTabTitle {
            get {
                return ResourceManager.GetString("MainTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned Decks.
        /// </summary>
        internal static string PinnedDecks {
            get {
                return ResourceManager.GetString("PinnedDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Date.
        /// </summary>
        internal static string PracticeDate {
            get {
                return ResourceManager.GetString("PracticeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice History.
        /// </summary>
        internal static string PracticeHistory {
            get {
                return ResourceManager.GetString("PracticeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Results.
        /// </summary>
        internal static string PracticeResults {
            get {
                return ResourceManager.GetString("PracticeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Results in Detail.
        /// </summary>
        internal static string PracticeResultsDetails {
            get {
                return ResourceManager.GetString("PracticeResultsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Cards.
        /// </summary>
        internal static string ProblemCards {
            get {
                return ResourceManager.GetString("ProblemCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Cards.
        /// </summary>
        internal static string SearchCards {
            get {
                return ResourceManager.GetString("SearchCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Decks.
        /// </summary>
        internal static string SearchDecks {
            get {
                return ResourceManager.GetString("SearchDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Templates.
        /// </summary>
        internal static string SearchTemplates {
            get {
                return ResourceManager.GetString("SearchTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan.
        /// </summary>
        internal static string Timespan {
            get {
                return ResourceManager.GetString("Timespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        internal static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
