// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacedRepetitionSystem.Entities.Core;

namespace SpacedRepetitionSystem.Entities.Migrations
{
    [DbContext(typeof(SpacedRepetionSystemDBContext))]
    [Migration("20200509135304_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Card", b =>
                {
                    b.Property<long>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("CardId");

                    b.HasIndex("CardTemplateId");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardField", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId", "FieldName");

                    b.HasIndex("CardTemplateId", "FieldName");

                    b.ToTable("CardFields","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardFieldDefinition", b =>
                {
                    b.Property<long>("CardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("ShowInputForPractice")
                        .HasColumnType("bit");

                    b.HasKey("CardTemplateId", "FieldName");

                    b.ToTable("CardFieldDefinitions","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", b =>
                {
                    b.Property<long>("CardTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CardTemplateId");

                    b.ToTable("CardTemplates","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", b =>
                {
                    b.Property<long>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DefaultCardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("DeckId");

                    b.HasIndex("DefaultCardTemplateId");

                    b.ToTable("Decks","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeField", b =>
                {
                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DeckId", "CardId", "FieldName");

                    b.HasIndex("CardId", "FieldName")
                        .IsUnique();

                    b.ToTable("PracticeFields","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeHistoryEntry", b =>
                {
                    b.Property<long>("PracticeHistoryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HardCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PracticeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("PracticeHistoryEntryId");

                    b.HasIndex("CardId")
                        .IsUnique(false);

                    b.HasIndex("DeckId");

                    b.HasIndex("CardId", "FieldName")
                        .IsUnique(false);

                    b.ToTable("PracticeHistoryEntries","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Card", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "CardTemplate")
                        .WithMany()
                        .HasForeignKey("CardTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardField", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Card", "Card")
                        .WithMany("Fields")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "CardTemplate")
                        .WithMany()
                        .HasForeignKey("CardTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardFieldDefinition", "CardFieldDefinition")
                        .WithMany()
                        .HasForeignKey("CardTemplateId", "FieldName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardFieldDefinition", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "CardTemplate")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("CardTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "DefaultCardTemplate")
                        .WithMany()
                        .HasForeignKey("DefaultCardTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeField", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Card", "Card")
                        .WithMany("PracticeFields")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", "Deck")
                        .WithMany("PracticeFields")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardField", "Field")
                        .WithOne()
                        .HasForeignKey("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeField", "CardId", "FieldName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeHistoryEntry", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Card", "Card")
                        .WithOne()
                        .HasForeignKey("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeHistoryEntry", "CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardField", "Field")
                        .WithOne()
                        .HasForeignKey("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeHistoryEntry", "CardId", "FieldName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
