// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacedRepetitionSystem.Entities.Core;

namespace SpacedRepetitionSystem.Entities.Migrations
{
    [DbContext(typeof(SpacedRepetionSystemDBContext))]
    partial class SpacedRepetionSystemDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Card", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("UserId", "CardId");

                    b.HasIndex("UserId", "CardTemplateId");

                    b.HasIndex("UserId", "DeckId");

                    b.ToTable("Cards","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardField", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "CardId", "FieldName");

                    b.HasIndex("UserId", "CardTemplateId", "FieldName");

                    b.ToTable("CardFields","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardFieldDefinition", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("ShowInputForPractice")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "CardTemplateId", "FieldName");

                    b.ToTable("CardFieldDefinitions","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CardTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("UserId", "CardTemplateId");

                    b.ToTable("CardTemplates","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DefaultCardTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("UserId", "DeckId");

                    b.HasIndex("UserId", "DefaultCardTemplateId");

                    b.ToTable("Decks","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeHistoryEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PracticeHistoryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HardCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PracticeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PracticeHistoryEntryId");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("PracticeHistoryEntries","Cards");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Security.RefreshToken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens","Security");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Security.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users","Security");
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Card", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "CardTemplate")
                        .WithMany()
                        .HasForeignKey("UserId", "CardTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("UserId", "DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardField", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.Card", "Card")
                        .WithMany("Fields")
                        .HasForeignKey("UserId", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "CardTemplate")
                        .WithMany()
                        .HasForeignKey("UserId", "CardTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardFieldDefinition", "CardFieldDefinition")
                        .WithMany()
                        .HasForeignKey("UserId", "CardTemplateId", "FieldName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardFieldDefinition", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "CardTemplate")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("UserId", "CardTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.Deck", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Cards.CardTemplate", "DefaultCardTemplate")
                        .WithMany()
                        .HasForeignKey("UserId", "DefaultCardTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Cards.PracticeHistoryEntry", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpacedRepetitionSystem.Entities.Entities.Security.RefreshToken", b =>
                {
                    b.HasOne("SpacedRepetitionSystem.Entities.Entities.Security.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
